'use client';

import { Inter } from 'next/font/google';
import React from 'react';
import { CheckUser } from '../components/CheckUser';
import Footer from '../components/Footer/Footer';
import Navbar from '../components/Navbar/Navbar';
import { Providers } from '../redux/provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Quiz Bee',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <Providers>
                    <CheckUser>
                        <Navbar />
                        {children}
                        <Footer />
                    </CheckUser>
                </Providers>
            </body>
        </html>
    );
}
